services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
      - CLIENT_URL=http://localhost:81
    restart: unless-stopped
    networks:
      - collectai-net

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - server
    restart: unless-stopped
    networks:
      - collectai-net

networks:
  collectai-net:
    driver: bridge
